-- ═══════════════════════════════════════════════════════════════════════════
-- WorkManagementPTSIVP - FULL DATABASE SCHEMA - 01. TABLES
-- ═══════════════════════════════════════════════════════════════════════════
-- Auto-generated by introspecting the live Supabase project (frxdbqcojaiosjoghdqk)
-- on 2026-08-30. This is the STRUCTURE (columns/types/defaults) only.
-- See 02_constraints.sql, 03_indexes.sql, 04_rls.sql, 05_functions_triggers.sql
-- for the rest, and README.md in this folder for the full apply order.
--
-- Requires the pgcrypto extension for gen_random_uuid():
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid,
  handler_name text NOT NULL,
  handler_username text,
  action_taken text,
  notes text NOT NULL,
  file_url text,
  file_name text,
  new_status text,
  created_at timestamp with time zone DEFAULT now(),
  team_type text,
  assigned_to_services boolean DEFAULT false,
  photo_url text,
  photo_name text
);

CREATE TABLE public.app_settings (
  key text NOT NULL,
  value jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.audit_trail (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text,
  user_name text,
  action character varying(50) NOT NULL,
  module character varying(100) NOT NULL,
  target_id text,
  target_name text,
  old_value text,
  new_value text,
  notes text,
  ip_address character varying(50),
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.brand_pic_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  brand_type text NOT NULL,
  brand_name text NOT NULL,
  pic_user_id uuid,
  pic_user_name text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.daily_report_team_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_date date NOT NULL,
  member_user_id uuid,
  member_name text NOT NULL,
  category text NOT NULL,
  project_name text NOT NULL,
  address text,
  sales_name text,
  sales_division text,
  supervisor_notes text,
  entered_by text NOT NULL,
  source text NOT NULL DEFAULT 'manual'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.daily_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_date date NOT NULL,
  user_id uuid,
  user_name text NOT NULL,
  sales_division text,
  reminder_activities jsonb NOT NULL DEFAULT '[]'::jsonb,
  ticket_activities jsonb NOT NULL DEFAULT '[]'::jsonb,
  manual_activities jsonb NOT NULL DEFAULT '[]'::jsonb,
  reminder_notes text,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone
);

CREATE TABLE public.division_ivp_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_division text NOT NULL,
  ivp_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  brand_type text
);

CREATE TABLE public.division_supervisor_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_division text NOT NULL,
  supervisor_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.form_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reminder_id uuid NOT NULL,
  project_name text,
  address text,
  sales_name text,
  sales_division text,
  assign_name text,
  assigned_to text,
  reminder_category text,
  review_category text,
  product_demo text,
  grade_product_knowledge integer,
  catatan_grade_product_knowledge text,
  product_bast text,
  grade_training_customer integer,
  catatan_grade_training_customer text,
  grade_product_knowledge_bast integer,
  catatan_grade_product_knowledge_bast text,
  foto_dokumentasi_url text,
  guest_fullname text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  guest_username text DEFAULT ''::text,
  batch_id uuid,
  sales_user_id uuid,
  guest_user_id uuid
);

-- Tabel bantu identitas/migrasi UUID (lihat sql/identitas-uuid*.sql) - boleh
-- dilewati pada instalasi baru, tidak dipakai fitur aplikasi manapun.
CREATE TABLE public.identitas_calon (
  tabel text,
  kolom text,
  nilai text,
  jumlah_baris bigint,
  user_id uuid,
  nama_akun text,
  cara text
);

CREATE TABLE public.identitas_sisa (
  tabel text,
  kolom text,
  nilai text,
  jumlah_baris bigint
);

CREATE TABLE public.identitas_usulan (
  tabel text NOT NULL,
  kolom text NOT NULL,
  nilai text NOT NULL,
  jumlah_baris bigint,
  user_id uuid NOT NULL,
  nama_akun text,
  cara text
);

-- incentive_disbursements/incentive_projects: skema insentif LAMA (sebelum
-- reminders.bast_date + incentive_tranches/incentive_splits). Ditulis, tidak
-- pernah dibaca kode aplikasi manapun sekarang - dipertahankan hanya untuk
-- riwayat pembayaran lama. Boleh dilewati pada instalasi baru/tanpa riwayat.
CREATE TABLE public.incentive_disbursements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  person_name text NOT NULL,
  person_username text,
  role_type text NOT NULL,
  pct numeric(5,2),
  amount_rp numeric(15,2),
  periode text,
  created_at timestamp with time zone DEFAULT now(),
  payment_year_1_paid boolean DEFAULT false,
  payment_year_2_paid boolean DEFAULT false,
  payment_year_3_paid boolean DEFAULT false,
  member_status text DEFAULT 'active'::text,
  resigned_at timestamp with time zone,
  redistributed_to jsonb
);

CREATE TABLE public.incentive_projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reminder_id uuid,
  project_name text NOT NULL,
  category text NOT NULL,
  sales_name text,
  sales_division text,
  due_date date,
  handler_name text NOT NULL,
  handler_username text,
  backup_names text[] DEFAULT '{}'::text[],
  biaya_cadangan numeric(15,2) DEFAULT 0,
  biaya_input_by text,
  biaya_input_at timestamp with time zone,
  periode text,
  status text DEFAULT 'pending'::text,
  paid_at timestamp with time zone,
  paid_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cos_project_no text,
  mode_penyelesaian character varying(10),
  installer_name text,
  installer_daerah text,
  installer_incentive_pct numeric(5,2) DEFAULT 0,
  installer_incentive_nominal numeric(15,2) DEFAULT 0,
  atasan_name text,
  address text,
  description text,
  notes text,
  pic_name text,
  pic_phone text,
  product text,
  supervisor_name text,
  installer_paid boolean DEFAULT false
);

-- Sumber tunggal skema pembagian insentif PTS (Scheme Setting). Setiap Simpan
-- menambah baris BARU (riwayat versi) - ambilSkema() selalu membaca baris
-- ber-updated_at TERBARU. Lihat lib/incentive-scheme.ts.
CREATE TABLE public.incentive_scheme_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scheme jsonb NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by text
);

-- Skema LAMA handler/backup (dipakai incentive_disbursements). Dipertahankan
-- untuk kompatibilitas riwayat, bukan sumber skema yang aktif dipakai layar
-- Incentive PTS saat ini (lihat incentive_scheme_settings).
CREATE TABLE public.incentive_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  handler_pct numeric(5,2) NOT NULL DEFAULT 70.00,
  backup_pct numeric(5,2) NOT NULL DEFAULT 30.00,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now(),
  pts_supervisor_username text,
  pts_manager_username text
);

-- Pembagian NOMINAL per orang per tahapan (hasil Process Batch). project_id
-- merujuk reminders.id (BUKAN incentive_projects.id) - lihat incentive_tranches.
CREATE TABLE public.incentive_splits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  tranche_id uuid,
  role text NOT NULL,
  user_id uuid,
  user_name text,
  percentage numeric NOT NULL,
  amount numeric,
  source_ticket_id uuid,
  created_at timestamp with time zone DEFAULT now()
);

-- Tahapan pencairan (T1/T2/T3) satu project. project_id merujuk reminders.id.
-- scheme_snapshot MEMBEKUKAN skema yang berlaku saat tahapan dibuat, supaya
-- perubahan skema di kemudian hari tidak mengubah tahapan yang sudah ada.
CREATE TABLE public.incentive_tranches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  tranche_number integer NOT NULL,
  percentage numeric NOT NULL,
  payment_year integer NOT NULL,
  status text DEFAULT 'pending'::text,
  processed_at timestamp with time zone,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  scheme_snapshot jsonb,
  scheme_label text
);

CREATE TABLE public.kpi_global_settings (
  id integer NOT NULL DEFAULT 1,
  settings jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.kpi_manual_values (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  year integer NOT NULL,
  komplain_count integer DEFAULT 0,
  respon_time integer DEFAULT 0,
  learning_mastery integer DEFAULT 0,
  bast_demo integer DEFAULT 0,
  bast_demo_total integer DEFAULT 0,
  report_bulanan integer DEFAULT 0,
  updated_by text,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.kpi_period_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  period_label text NOT NULL,
  year integer NOT NULL,
  period text NOT NULL,
  start_month integer NOT NULL,
  end_month integer NOT NULL,
  team_type text NOT NULL,
  created_by text,
  members_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  settings_json jsonb,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.kpi_snapshot_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  snapshot_id uuid NOT NULL,
  member_id text NOT NULL,
  name text NOT NULL,
  jabatan text,
  team_type text,
  tickets_handled integer DEFAULT 0,
  tickets_solved integer DEFAULT 0,
  tickets_overdue integer DEFAULT 0,
  lc_attempts integer DEFAULT 0,
  lc_avg_score numeric(6,2) DEFAULT 0,
  lc_passed integer DEFAULT 0,
  form_review_total integer DEFAULT 0,
  form_review_low integer DEFAULT 0,
  tech_notes_approved integer DEFAULT 0,
  tick_score smallint DEFAULT 0,
  bast_score smallint DEFAULT 0,
  lc_score smallint DEFAULT 0,
  rnd_score smallint DEFAULT 0,
  final_kpi smallint DEFAULT 0
);

CREATE TABLE public.late_ticket_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  late_ticket_id uuid,
  parent_project_id uuid NOT NULL,
  attached_tranche_number integer NOT NULL,
  attached_at timestamp with time zone DEFAULT now(),
  note text,
  ticket_value numeric DEFAULT 0,
  is_sunset boolean DEFAULT false
);

CREATE TABLE public.lc_answers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attempt_id uuid,
  user_id uuid,
  quiz_session_id uuid,
  question_id uuid,
  answer character(1),
  is_correct boolean,
  answered_at timestamp with time zone DEFAULT now(),
  essay_text text,
  manual_score numeric,
  ai_score numeric,
  ai_feedback text,
  answer_image_url text,
  answer_thumb_url text
);

CREATE TABLE public.lc_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  materi_name text NOT NULL,
  content_text text,
  file_url text,
  file_name text,
  file_type text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  folder_path text
);

CREATE TABLE public.lc_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_id uuid,
  materi_name text NOT NULL,
  question text NOT NULL,
  option_a text,
  option_b text,
  option_c text,
  option_d text,
  correct_answer character(1),
  difficulty text DEFAULT 'medium'::text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  batch_name text,
  question_type text NOT NULL DEFAULT 'abcd'::text,
  model_answer text,
  answer_format text NOT NULL DEFAULT 'text'::text,
  urutan integer
);

CREATE TABLE public.lc_quiz_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  quiz_session_id uuid,
  started_at timestamp with time zone DEFAULT now(),
  submitted_at timestamp with time zone,
  score numeric(5,2),
  total_correct integer DEFAULT 0,
  total_questions integer DEFAULT 0,
  passed boolean,
  time_taken_sec integer,
  is_submitted boolean DEFAULT false,
  tab_switches integer DEFAULT 0,
  grading_status text NOT NULL DEFAULT 'auto'::text,
  graded_by uuid,
  graded_at timestamp with time zone
);

CREATE TABLE public.lc_quiz_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_name text NOT NULL,
  material_id uuid,
  materi_name text NOT NULL,
  question_ids uuid[],
  question_count integer NOT NULL DEFAULT 10,
  timer_minutes integer DEFAULT 30,
  passing_grade integer DEFAULT 70,
  is_active boolean DEFAULT true,
  allow_retake boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  scheduled_at timestamp with time zone,
  closed_at timestamp with time zone,
  target_user_ids uuid[],
  open_at timestamp with time zone,
  close_at timestamp with time zone,
  session_type text NOT NULL DEFAULT 'abcd'::text
);

CREATE TABLE public.login_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL,
  ip_address text,
  attempted_at timestamp with time zone DEFAULT now(),
  success boolean DEFAULT false
);

CREATE TABLE public.movement_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tanggal date NOT NULL,
  nama_pts text,
  nama_luar text,
  status_barang text,
  event text,
  project_name text,
  type_barang text,
  serial_number text,
  catatan text,
  foto_surat_url text,
  foto_barang_url text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  kondisi_barang character varying(50),
  expected_return_date date,
  return_confirmed boolean DEFAULT false,
  checkout_reference_id uuid,
  is_deleted boolean DEFAULT false,
  deleted_by text,
  deleted_at timestamp with time zone
);

CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  type character varying(50) NOT NULL DEFAULT 'system'::character varying,
  title text NOT NULL,
  body text,
  action_url character varying(255),
  ref_id text,
  created_by text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.overdue_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ticket_id uuid,
  due_date timestamp with time zone,
  due_hours integer,
  set_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.password_reset_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL,
  otp_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.picket_holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date text NOT NULL,
  label text NOT NULL DEFAULT 'Libur'::text,
  created_by text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.piket_produk_lain (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kegiatan_id uuid,
  piket_id uuid,
  nama text NOT NULL DEFAULT ''::text,
  watt integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.piket_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  week_start date NOT NULL,
  day_of_week text NOT NULL,
  day_date date,
  pic_ivp_id uuid,
  pic_ivp_name text,
  pic_ump_id uuid,
  pic_ump_name text,
  pic_mvi_id uuid,
  pic_mvi_name text,
  tamu_instansi text,
  kebutuhan text[] DEFAULT '{}'::text[],
  foto_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  edited_by_name text
);

CREATE TABLE public.piket_tamu_detail (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  piket_id uuid,
  tamu_instansi text,
  nama_sales text,
  sales_division text,
  kebutuhan text[] DEFAULT '{}'::text[],
  foto_url text,
  created_at timestamp with time zone DEFAULT now(),
  keterangan text,
  jam_mulai time without time zone,
  jam_selesai time without time zone,
  produk text[] DEFAULT '{}'::text[],
  jenis_kegiatan text DEFAULT 'Demo Product'::text,
  team_rnd text,
  edited_by_name text,
  updated_at timestamp with time zone
);

CREATE TABLE public.product_team_map (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_type text NOT NULL,
  team_types text[] NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.progress_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  issue_id uuid NOT NULL,
  description text NOT NULL,
  pic text,
  target_date date,
  status text NOT NULL DEFAULT 'open'::text,
  notes text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone
);

CREATE TABLE public.progress_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id uuid NOT NULL,
  label text NOT NULL,
  state text NOT NULL DEFAULT 'pending'::text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  photo_url text,
  photo_thumb_url text,
  weight numeric NOT NULL DEFAULT 1,
  category text
);

CREATE TABLE public.progress_issues (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  location_label text,
  issue text NOT NULL,
  severity text NOT NULL DEFAULT 'sedang'::text,
  note text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  pic text,
  status text NOT NULL DEFAULT 'open'::text,
  due_date date,
  root_cause text,
  action_plan text,
  resolution text,
  resolved_at timestamp with time zone,
  location_id uuid,
  component_id uuid
);

CREATE TABLE public.progress_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  name text NOT NULL,
  pic text,
  status text NOT NULL DEFAULT 'in_progress'::text,
  progress integer NOT NULL DEFAULT 0,
  note text,
  note_flag boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  start_date date,
  target_date date,
  sales_name text,
  sales_division text,
  origin text NOT NULL DEFAULT 'manual'::text,
  source_reminder_id uuid,
  sales_user_id uuid,
  pic_user_id uuid
);

CREATE TABLE public.progress_projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  client text,
  description text,
  status text NOT NULL DEFAULT 'in_progress'::text,
  share_token text,
  share_enabled boolean NOT NULL DEFAULT false,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  start_date date,
  target_date date,
  sales_name text,
  sales_division text,
  origin text NOT NULL DEFAULT 'manual'::text,
  source_reminder_id uuid,
  sales_user_id uuid
);

CREATE TABLE public.project_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid,
  message_id uuid,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_type text NOT NULL,
  file_size bigint NOT NULL,
  uploaded_by text NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  attachment_category text DEFAULT 'general'::text,
  revision_version integer
);

CREATE TABLE public.project_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_id uuid,
  sender_id text NOT NULL,
  sender_name text NOT NULL,
  sender_role text NOT NULL,
  message text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.project_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  project_name text NOT NULL,
  room_name text,
  sales_name text,
  requester_id text NOT NULL,
  requester_name text NOT NULL,
  status text DEFAULT 'pending'::text,
  kebutuhan jsonb DEFAULT '[]'::jsonb,
  kebutuhan_other text DEFAULT ''::text,
  solution_product jsonb DEFAULT '[]'::jsonb,
  solution_other text DEFAULT ''::text,
  layout_signage jsonb DEFAULT '[]'::jsonb,
  jaringan_cms jsonb DEFAULT '[]'::jsonb,
  jumlah_input text DEFAULT ''::text,
  jumlah_output text DEFAULT ''::text,
  source jsonb DEFAULT '[]'::jsonb,
  source_other text DEFAULT ''::text,
  camera_conference text DEFAULT 'No'::text,
  camera_jumlah text DEFAULT ''::text,
  camera_tracking jsonb DEFAULT '[]'::jsonb,
  audio_system text DEFAULT 'No'::text,
  audio_detail jsonb DEFAULT '[]'::jsonb,
  wallplate_input text DEFAULT 'No'::text,
  wallplate_jumlah text DEFAULT ''::text,
  wireless_presentation text DEFAULT 'No'::text,
  ukuran_ruangan text DEFAULT ''::text,
  suggest_tampilan text DEFAULT ''::text,
  keterangan_lain text DEFAULT ''::text,
  assign_name text,
  approved_by text,
  approved_at timestamp with time zone,
  due_date timestamp with time zone DEFAULT now(),
  audio_mixer text DEFAULT ''::text,
  tabletop_input text DEFAULT 'No'::text,
  tabletop_jumlah text DEFAULT ''::text,
  wireless_mode text[] DEFAULT '{}'::text[],
  wireless_dongle text DEFAULT 'No'::text,
  controller_automation text DEFAULT 'No'::text,
  controller_type text[] DEFAULT '{}'::text[],
  assigned_handler text,
  sales_division text,
  project_location text,
  ivp_assignee text,
  rooms jsonb DEFAULT '[]'::jsonb,
  brand_display text,
  brand_display_pic_id uuid,
  brand_display_pic_name text,
  brand_middleware text,
  brand_middleware_pic_id uuid,
  brand_middleware_pic_name text,
  is_deleted boolean DEFAULT false,
  deleted_by text,
  deleted_at timestamp with time zone,
  rejection_reason text,
  routing_status text,
  internal_sales_id uuid,
  internal_approved_by uuid,
  internal_approved_at timestamp with time zone,
  assigned_supervisor_id uuid,
  brand text,
  internal_sales_id_2 uuid,
  internal_approved_at_2 timestamp with time zone,
  brand_display_2 text,
  brand_display_2_pic_id text,
  brand_display_2_pic_name text,
  sales_user_id uuid,
  assign_user_id uuid
);

CREATE TABLE public.pts_team_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_user_id uuid NOT NULL,
  supervisor_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Kredensial integrasi pihak ketiga (mis. kunci API). NILAI KOSONG di
-- instalasi baru - isi ulang lewat aplikasi (Admin Panel), JANGAN copy nilai
-- dari instalasi lama ke instalasi Company baru.
CREATE TABLE public.rahasia_integrasi (
  kunci text NOT NULL,
  nilai text NOT NULL,
  diperbarui_pada timestamp with time zone NOT NULL DEFAULT now(),
  diperbarui_oleh text
);

-- Tabel INTI - jadwal/Reminder Schedule, juga sumber "Incentive PTS Project"
-- (lihat kolom bast_date, incentive_value, incentive_excluded, incentive_group_id).
CREATE TABLE public.reminders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_name text NOT NULL,
  description text DEFAULT ''::text,
  assigned_to text NOT NULL,
  assign_name text NOT NULL,
  due_date date NOT NULL,
  due_time time without time zone DEFAULT '09:00:00'::time without time zone,
  priority text DEFAULT 'medium'::text,
  status text DEFAULT 'pending'::text,
  repeat text DEFAULT 'none'::text,
  category text DEFAULT 'Umum'::text,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  notes text DEFAULT ''::text,
  sales_name text DEFAULT ''::text,
  address text DEFAULT ''::text,
  pic_name text,
  pic_phone text,
  completion_photo_url text,
  sales_division text,
  product text,
  guest_fullname text,
  warranty_years smallint,
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  deleted_by text,
  deleted_at timestamp with time zone,
  mode_penyelesaian character varying(10),
  installer_name text,
  installer_daerah text,
  installer_user_id uuid,
  requires_controller_automation boolean DEFAULT false,
  controller_automation_brand text,
  pic_type text DEFAULT 'standard'::text,
  pic_id uuid,
  domain_owner text,
  bast_date date,
  incentive_value numeric DEFAULT 0,
  display_type text,
  requires_middleware boolean DEFAULT false,
  execution_mode text,
  product_type text,
  batch_id uuid,
  routing_status text,
  internal_sales_id uuid,
  internal_approved_by uuid,
  internal_approved_at timestamp with time zone,
  rejection_reason text,
  assigned_supervisor_id uuid,
  brand text,
  internal_sales_id_2 uuid,
  internal_approved_at_2 timestamp with time zone,
  progress_start_date date,
  progress_target_date date,
  sales_user_id uuid,
  assign_user_id uuid,
  incentive_tarif_kunci text,
  incentive_dasar_hpp numeric,
  incentive_excluded boolean DEFAULT false,
  incentive_group_id uuid
);

-- Pelacak SQL yang sudah dijalankan manual (sql/ folder) - dokumentasi, bukan
-- migration runner otomatis. Boleh dikosongkan di instalasi baru.
CREATE TABLE public.sql_diterapkan (
  berkas text NOT NULL,
  urutan integer NOT NULL,
  golongan text NOT NULL,
  diterapkan_pada timestamp with time zone,
  catatan text
);

CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  username text,
  photo_url text,
  role text,
  created_at timestamp without time zone DEFAULT now(),
  team_type text
);

CREATE TABLE public.tech_note_folders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  icon text NOT NULL DEFAULT '📄'::text,
  color text NOT NULL DEFAULT '#ec4899'::text,
  parent_id uuid,
  description text,
  created_by text NOT NULL DEFAULT 'Admin'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  category text
);

CREATE TABLE public.tech_note_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tech_note_id uuid NOT NULL,
  action text NOT NULL,
  performed_by text NOT NULL,
  performed_by_name text NOT NULL,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.tech_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  folder_id uuid NOT NULL,
  author_id text NOT NULL,
  author_name text NOT NULL,
  one_drive_link text NOT NULL,
  product text NOT NULL DEFAULT ''::text,
  tags text[] NOT NULL DEFAULT '{}'::text[],
  team_type text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'pending'::text,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_at timestamp with time zone,
  reviewed_by text,
  reviewed_by_name text,
  review_note text
);

CREATE TABLE public.ticket_support_assignment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid,
  project_id uuid,
  user_id uuid NOT NULL,
  user_name text,
  domain text NOT NULL,
  assigned_by uuid,
  assigned_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_name text NOT NULL,
  sales_name text,
  customer_phone text,
  issue_case text NOT NULL,
  description text,
  assign_name text NOT NULL,
  status text DEFAULT 'Pending'::text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  date date DEFAULT CURRENT_DATE,
  created_by text,
  sn_unit text,
  current_team text,
  services_status text,
  address text,
  photo_url text,
  photo_name text,
  overdue_hours numeric,
  sales_division text,
  product text,
  is_deleted boolean DEFAULT false,
  deleted_by text,
  deleted_at timestamp with time zone,
  rejection_reason text,
  reminder_id uuid,
  escalation_notified_at timestamp with time zone,
  priority text DEFAULT 'Medium'::text,
  assigned_supervisor_id uuid,
  routing_status text,
  internal_sales_id uuid,
  brand text,
  internal_sales_id_2 uuid,
  sales_user_id uuid,
  assign_user_id uuid
);

CREATE TABLE public.user_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  password_hash text NOT NULL,
  algorithm text NOT NULL DEFAULT 'bcrypt'::text,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL,
  ip_address text,
  user_agent text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.user_supervisor_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  supervisor_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Tabel INTI - akun aplikasi (bukan auth.users Supabase - login custom lewat
-- user_credentials/user_sessions). role/team_type/allow_incentive_input/
-- allowed_menus/access_level DIJAGA trigger guard_users_privileged_columns
-- (lihat 05_functions_triggers.sql) - hanya bisa diubah lewat service_role
-- (server-side), bukan langsung dari klien.
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL,
  role text DEFAULT 'team'::text,
  full_name text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  team_type text,
  phone_number text,
  allowed_menus text[] DEFAULT ARRAY['form-bast'::text, 'ticket-troubleshooting'::text, 'daily-report'::text, 'database-pts'::text, 'unit-movement'::text],
  sales_division text,
  jabatan text,
  kpi_enabled boolean NOT NULL DEFAULT true,
  allow_incentive_input boolean DEFAULT false,
  divisi character varying(50),
  pts_type character varying(50),
  atasan_id uuid,
  is_internal_sales boolean NOT NULL DEFAULT false,
  access_level text NOT NULL DEFAULT 'guest'::text,
  incentive_brand_scope text,
  pts_daerah text
);
