-- ═══════════════════════════════════════════════════════════════════════════
-- 02. CONSTRAINTS (PRIMARY KEY / UNIQUE / FOREIGN KEY / CHECK)
-- ═══════════════════════════════════════════════════════════════════════════
-- Jalankan SESUDAH 01_tables.sql (semua tabel harus sudah ada).

ALTER TABLE public.activity_logs ADD CONSTRAINT activity_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.activity_logs ADD CONSTRAINT activity_logs_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE public.app_settings ADD CONSTRAINT app_settings_pkey PRIMARY KEY (key);
ALTER TABLE public.audit_trail ADD CONSTRAINT audit_trail_pkey PRIMARY KEY (id);
ALTER TABLE public.brand_pic_mappings ADD CONSTRAINT brand_pic_mappings_pkey PRIMARY KEY (id);
ALTER TABLE public.brand_pic_mappings ADD CONSTRAINT brand_pic_mappings_brand_type_brand_name_key UNIQUE (brand_type, brand_name);
ALTER TABLE public.brand_pic_mappings ADD CONSTRAINT brand_pic_mappings_pic_user_id_fkey FOREIGN KEY (pic_user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE public.daily_report_team_entries ADD CONSTRAINT daily_report_team_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.daily_report_team_entries ADD CONSTRAINT daily_report_team_entries_member_user_id_fkey FOREIGN KEY (member_user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE public.daily_reports ADD CONSTRAINT daily_reports_pkey PRIMARY KEY (id);
ALTER TABLE public.daily_reports ADD CONSTRAINT uq_daily_report_user_date UNIQUE (user_id, report_date);
ALTER TABLE public.daily_reports ADD CONSTRAINT daily_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.division_ivp_mappings ADD CONSTRAINT division_ivp_mappings_pkey PRIMARY KEY (id);
ALTER TABLE public.division_ivp_mappings ADD CONSTRAINT division_ivp_mappings_division_brand_key UNIQUE (sales_division, brand_type);
ALTER TABLE public.division_ivp_mappings ADD CONSTRAINT division_ivp_mappings_sales_division_ivp_id_key UNIQUE (sales_division, ivp_id);
ALTER TABLE public.division_ivp_mappings ADD CONSTRAINT division_ivp_mappings_ivp_id_fkey FOREIGN KEY (ivp_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.division_supervisor_mappings ADD CONSTRAINT division_supervisor_mappings_pkey PRIMARY KEY (id);
ALTER TABLE public.division_supervisor_mappings ADD CONSTRAINT division_supervisor_mappings_sales_division_supervisor_id_key UNIQUE (sales_division, supervisor_id);
ALTER TABLE public.division_supervisor_mappings ADD CONSTRAINT division_supervisor_mappings_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.form_reviews ADD CONSTRAINT form_reviews_pkey PRIMARY KEY (id);
ALTER TABLE public.form_reviews ADD CONSTRAINT form_reviews_grade_product_knowledge_bast_check CHECK (((grade_product_knowledge_bast >= 1) AND (grade_product_knowledge_bast <= 5)));
ALTER TABLE public.form_reviews ADD CONSTRAINT form_reviews_grade_product_knowledge_check CHECK (((grade_product_knowledge >= 1) AND (grade_product_knowledge <= 5)));
ALTER TABLE public.form_reviews ADD CONSTRAINT form_reviews_grade_training_customer_check CHECK (((grade_training_customer >= 1) AND (grade_training_customer <= 5)));
ALTER TABLE public.form_reviews ADD CONSTRAINT form_reviews_review_category_check CHECK ((review_category = ANY (ARRAY['Demo Product'::text, 'BAST'::text])));
ALTER TABLE public.incentive_disbursements ADD CONSTRAINT incentive_disbursements_pkey PRIMARY KEY (id);
ALTER TABLE public.incentive_disbursements ADD CONSTRAINT incentive_disbursements_project_id_fkey FOREIGN KEY (project_id) REFERENCES incentive_projects(id) ON DELETE CASCADE;
ALTER TABLE public.incentive_disbursements ADD CONSTRAINT incentive_disbursements_member_status_check CHECK ((member_status = ANY (ARRAY['active'::text, 'resigned'::text])));
ALTER TABLE public.incentive_projects ADD CONSTRAINT incentive_projects_pkey PRIMARY KEY (id);
ALTER TABLE public.incentive_projects ADD CONSTRAINT incentive_projects_reminder_id_fkey FOREIGN KEY (reminder_id) REFERENCES reminders(id) ON DELETE SET NULL;
ALTER TABLE public.incentive_scheme_settings ADD CONSTRAINT incentive_scheme_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.incentive_settings ADD CONSTRAINT incentive_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.incentive_splits ADD CONSTRAINT incentive_splits_pkey PRIMARY KEY (id);
ALTER TABLE public.incentive_splits ADD CONSTRAINT incentive_splits_project_id_fkey FOREIGN KEY (project_id) REFERENCES reminders(id) ON DELETE CASCADE;
ALTER TABLE public.incentive_splits ADD CONSTRAINT incentive_splits_tranche_id_fkey FOREIGN KEY (tranche_id) REFERENCES incentive_tranches(id) ON DELETE CASCADE;
ALTER TABLE public.incentive_splits ADD CONSTRAINT incentive_splits_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.incentive_tranches ADD CONSTRAINT incentive_tranches_pkey PRIMARY KEY (id);
ALTER TABLE public.incentive_tranches ADD CONSTRAINT incentive_tranches_project_id_fkey FOREIGN KEY (project_id) REFERENCES reminders(id) ON DELETE CASCADE;
ALTER TABLE public.incentive_tranches ADD CONSTRAINT incentive_tranches_tranche_number_check CHECK ((tranche_number >= 1));
ALTER TABLE public.kpi_global_settings ADD CONSTRAINT kpi_global_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.kpi_manual_values ADD CONSTRAINT kpi_manual_values_pkey PRIMARY KEY (id);
ALTER TABLE public.kpi_manual_values ADD CONSTRAINT kpi_manual_values_user_id_year_key UNIQUE (user_id, year);
ALTER TABLE public.kpi_manual_values ADD CONSTRAINT kpi_manual_values_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.kpi_period_snapshots ADD CONSTRAINT kpi_period_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.kpi_snapshot_members ADD CONSTRAINT kpi_snapshot_members_pkey PRIMARY KEY (id);
ALTER TABLE public.kpi_snapshot_members ADD CONSTRAINT kpi_snapshot_members_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES kpi_period_snapshots(id) ON DELETE CASCADE;
ALTER TABLE public.late_ticket_links ADD CONSTRAINT late_ticket_links_pkey PRIMARY KEY (id);
ALTER TABLE public.late_ticket_links ADD CONSTRAINT late_ticket_links_parent_project_id_fkey FOREIGN KEY (parent_project_id) REFERENCES reminders(id) ON DELETE CASCADE;
ALTER TABLE public.lc_answers ADD CONSTRAINT lc_answers_pkey PRIMARY KEY (id);
ALTER TABLE public.lc_answers ADD CONSTRAINT lc_answers_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES lc_quiz_attempts(id) ON DELETE CASCADE;
ALTER TABLE public.lc_answers ADD CONSTRAINT lc_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES lc_questions(id);
ALTER TABLE public.lc_answers ADD CONSTRAINT lc_answers_quiz_session_id_fkey FOREIGN KEY (quiz_session_id) REFERENCES lc_quiz_sessions(id);
ALTER TABLE public.lc_answers ADD CONSTRAINT lc_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.lc_answers ADD CONSTRAINT lc_answers_ai_score_range CHECK (((ai_score IS NULL) OR ((ai_score >= (0)::numeric) AND (ai_score <= (100)::numeric))));
ALTER TABLE public.lc_answers ADD CONSTRAINT lc_answers_answer_check CHECK (((answer IS NULL) OR (answer = ''::bpchar) OR (answer = ANY (ARRAY['A'::bpchar, 'B'::bpchar, 'C'::bpchar, 'D'::bpchar]))));
ALTER TABLE public.lc_answers ADD CONSTRAINT lc_answers_manual_score_range CHECK (((manual_score IS NULL) OR ((manual_score >= (0)::numeric) AND (manual_score <= (100)::numeric))));
ALTER TABLE public.lc_materials ADD CONSTRAINT lc_materials_pkey PRIMARY KEY (id);
ALTER TABLE public.lc_materials ADD CONSTRAINT lc_materials_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.lc_questions ADD CONSTRAINT lc_questions_pkey PRIMARY KEY (id);
ALTER TABLE public.lc_questions ADD CONSTRAINT lc_questions_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.lc_questions ADD CONSTRAINT lc_questions_material_id_fkey FOREIGN KEY (material_id) REFERENCES lc_materials(id) ON DELETE CASCADE;
ALTER TABLE public.lc_questions ADD CONSTRAINT lc_questions_answer_format_check CHECK ((answer_format = ANY (ARRAY['text'::text, 'image'::text])));
ALTER TABLE public.lc_questions ADD CONSTRAINT lc_questions_correct_answer_check CHECK ((correct_answer = ANY (ARRAY['A'::bpchar, 'B'::bpchar, 'C'::bpchar, 'D'::bpchar])));
ALTER TABLE public.lc_questions ADD CONSTRAINT lc_questions_difficulty_check CHECK ((difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])));
ALTER TABLE public.lc_questions ADD CONSTRAINT lc_questions_question_type_check CHECK ((question_type = ANY (ARRAY['abcd'::text, 'essay'::text])));
ALTER TABLE public.lc_quiz_attempts ADD CONSTRAINT lc_quiz_attempts_pkey PRIMARY KEY (id);
ALTER TABLE public.lc_quiz_attempts ADD CONSTRAINT lc_quiz_attempts_graded_by_fkey FOREIGN KEY (graded_by) REFERENCES users(id);
ALTER TABLE public.lc_quiz_attempts ADD CONSTRAINT lc_quiz_attempts_quiz_session_id_fkey FOREIGN KEY (quiz_session_id) REFERENCES lc_quiz_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.lc_quiz_attempts ADD CONSTRAINT lc_quiz_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.lc_quiz_attempts ADD CONSTRAINT lc_quiz_attempts_grading_status_check CHECK ((grading_status = ANY (ARRAY['auto'::text, 'pending_review'::text, 'graded'::text])));
ALTER TABLE public.lc_quiz_sessions ADD CONSTRAINT lc_quiz_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.lc_quiz_sessions ADD CONSTRAINT lc_quiz_sessions_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.lc_quiz_sessions ADD CONSTRAINT lc_quiz_sessions_material_id_fkey FOREIGN KEY (material_id) REFERENCES lc_materials(id);
ALTER TABLE public.lc_quiz_sessions ADD CONSTRAINT lc_quiz_sessions_session_type_check CHECK ((session_type = ANY (ARRAY['abcd'::text, 'essay'::text])));
ALTER TABLE public.login_attempts ADD CONSTRAINT login_attempts_pkey PRIMARY KEY (id);
ALTER TABLE public.movement_logs ADD CONSTRAINT movement_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.movement_logs ADD CONSTRAINT movement_logs_status_barang_check CHECK ((status_barang = ANY (ARRAY['Masuk'::text, 'Keluar'::text])));
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.overdue_settings ADD CONSTRAINT overdue_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.overdue_settings ADD CONSTRAINT overdue_settings_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE public.password_reset_otps ADD CONSTRAINT password_reset_otps_pkey PRIMARY KEY (id);
ALTER TABLE public.picket_holidays ADD CONSTRAINT picket_holidays_pkey PRIMARY KEY (id);
ALTER TABLE public.picket_holidays ADD CONSTRAINT picket_holidays_date_key UNIQUE (date);
ALTER TABLE public.piket_produk_lain ADD CONSTRAINT piket_produk_lain_pkey PRIMARY KEY (id);
ALTER TABLE public.piket_produk_lain ADD CONSTRAINT piket_produk_lain_kegiatan_id_fkey FOREIGN KEY (kegiatan_id) REFERENCES piket_tamu_detail(id) ON DELETE CASCADE;
ALTER TABLE public.piket_schedules ADD CONSTRAINT piket_schedules_pkey PRIMARY KEY (id);
ALTER TABLE public.piket_schedules ADD CONSTRAINT piket_schedules_week_start_day_of_week_key UNIQUE (week_start, day_of_week);
ALTER TABLE public.piket_schedules ADD CONSTRAINT piket_schedules_day_of_week_check CHECK ((day_of_week = ANY (ARRAY['Senin'::text, 'Selasa'::text, 'Rabu'::text, 'Kamis'::text, 'Jumat'::text])));
ALTER TABLE public.piket_tamu_detail ADD CONSTRAINT piket_tamu_detail_pkey PRIMARY KEY (id);
ALTER TABLE public.piket_tamu_detail ADD CONSTRAINT piket_tamu_detail_piket_id_fkey FOREIGN KEY (piket_id) REFERENCES piket_schedules(id) ON DELETE CASCADE;
ALTER TABLE public.product_team_map ADD CONSTRAINT product_team_map_pkey PRIMARY KEY (id);
ALTER TABLE public.product_team_map ADD CONSTRAINT product_team_map_product_type_key UNIQUE (product_type);
ALTER TABLE public.progress_actions ADD CONSTRAINT progress_actions_pkey PRIMARY KEY (id);
ALTER TABLE public.progress_actions ADD CONSTRAINT progress_actions_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES progress_issues(id) ON DELETE CASCADE;
ALTER TABLE public.progress_actions ADD CONSTRAINT progress_actions_status_check CHECK ((status = ANY (ARRAY['open'::text, 'in_progress'::text, 'done'::text])));
ALTER TABLE public.progress_components ADD CONSTRAINT progress_components_pkey PRIMARY KEY (id);
ALTER TABLE public.progress_components ADD CONSTRAINT progress_components_location_id_fkey FOREIGN KEY (location_id) REFERENCES progress_locations(id) ON DELETE CASCADE;
ALTER TABLE public.progress_components ADD CONSTRAINT progress_components_state_check CHECK ((state = ANY (ARRAY['done'::text, 'progress'::text, 'pending'::text, 'stuck'::text])));
ALTER TABLE public.progress_components ADD CONSTRAINT progress_components_weight_positive_check CHECK ((weight > (0)::numeric));
ALTER TABLE public.progress_issues ADD CONSTRAINT progress_issues_pkey PRIMARY KEY (id);
ALTER TABLE public.progress_issues ADD CONSTRAINT progress_issues_component_id_fkey FOREIGN KEY (component_id) REFERENCES progress_components(id) ON DELETE SET NULL;
ALTER TABLE public.progress_issues ADD CONSTRAINT progress_issues_location_id_fkey FOREIGN KEY (location_id) REFERENCES progress_locations(id) ON DELETE SET NULL;
ALTER TABLE public.progress_issues ADD CONSTRAINT progress_issues_project_id_fkey FOREIGN KEY (project_id) REFERENCES progress_projects(id) ON DELETE CASCADE;
ALTER TABLE public.progress_issues ADD CONSTRAINT progress_issues_severity_check CHECK ((severity = ANY (ARRAY['kritis'::text, 'tinggi'::text, 'sedang'::text, 'rendah'::text])));
ALTER TABLE public.progress_issues ADD CONSTRAINT progress_issues_status_check CHECK ((status = ANY (ARRAY['open'::text, 'in_progress'::text, 'waiting_vendor'::text, 'waiting_client'::text, 'resolved'::text, 'closed'::text])));
ALTER TABLE public.progress_locations ADD CONSTRAINT progress_locations_pkey PRIMARY KEY (id);
ALTER TABLE public.progress_locations ADD CONSTRAINT progress_locations_project_id_fkey FOREIGN KEY (project_id) REFERENCES progress_projects(id) ON DELETE CASCADE;
ALTER TABLE public.progress_locations ADD CONSTRAINT progress_locations_source_reminder_id_fkey FOREIGN KEY (source_reminder_id) REFERENCES reminders(id) ON DELETE SET NULL;
ALTER TABLE public.progress_locations ADD CONSTRAINT progress_locations_date_order_check CHECK (((start_date IS NULL) OR (target_date IS NULL) OR (target_date >= start_date)));
ALTER TABLE public.progress_locations ADD CONSTRAINT progress_locations_origin_check CHECK ((origin = ANY (ARRAY['manual'::text, 'auto_reminder'::text])));
ALTER TABLE public.progress_locations ADD CONSTRAINT progress_locations_progress_check CHECK (((progress >= 0) AND (progress <= 100)));
ALTER TABLE public.progress_projects ADD CONSTRAINT progress_projects_pkey PRIMARY KEY (id);
ALTER TABLE public.progress_projects ADD CONSTRAINT progress_projects_share_token_key UNIQUE (share_token);
ALTER TABLE public.progress_projects ADD CONSTRAINT progress_projects_source_reminder_id_fkey FOREIGN KEY (source_reminder_id) REFERENCES reminders(id) ON DELETE SET NULL;
ALTER TABLE public.progress_projects ADD CONSTRAINT progress_projects_date_order_check CHECK (((start_date IS NULL) OR (target_date IS NULL) OR (target_date >= start_date)));
ALTER TABLE public.progress_projects ADD CONSTRAINT progress_projects_origin_check CHECK ((origin = ANY (ARRAY['manual'::text, 'auto_reminder'::text])));
ALTER TABLE public.project_attachments ADD CONSTRAINT project_attachments_pkey PRIMARY KEY (id);
ALTER TABLE public.project_attachments ADD CONSTRAINT project_attachments_message_id_fkey FOREIGN KEY (message_id) REFERENCES project_messages(id) ON DELETE SET NULL;
ALTER TABLE public.project_attachments ADD CONSTRAINT project_attachments_request_id_fkey FOREIGN KEY (request_id) REFERENCES project_requests(id) ON DELETE CASCADE;
ALTER TABLE public.project_messages ADD CONSTRAINT project_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.project_messages ADD CONSTRAINT project_messages_request_id_fkey FOREIGN KEY (request_id) REFERENCES project_requests(id) ON DELETE CASCADE;
ALTER TABLE public.project_requests ADD CONSTRAINT project_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.project_requests ADD CONSTRAINT project_requests_internal_approved_by_fkey FOREIGN KEY (internal_approved_by) REFERENCES users(id);
ALTER TABLE public.project_requests ADD CONSTRAINT project_requests_internal_sales_id_fkey FOREIGN KEY (internal_sales_id) REFERENCES users(id);
ALTER TABLE public.pts_team_mappings ADD CONSTRAINT pts_team_mappings_pkey PRIMARY KEY (id);
ALTER TABLE public.pts_team_mappings ADD CONSTRAINT pts_team_mappings_staff_user_id_key UNIQUE (staff_user_id);
ALTER TABLE public.pts_team_mappings ADD CONSTRAINT pts_team_mappings_staff_user_id_fkey FOREIGN KEY (staff_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.pts_team_mappings ADD CONSTRAINT pts_team_mappings_supervisor_user_id_fkey FOREIGN KEY (supervisor_user_id) REFERENCES users(id);
ALTER TABLE public.rahasia_integrasi ADD CONSTRAINT rahasia_integrasi_pkey PRIMARY KEY (kunci);
ALTER TABLE public.reminders ADD CONSTRAINT reminders_pkey PRIMARY KEY (id);
ALTER TABLE public.reminders ADD CONSTRAINT reminders_assigned_supervisor_id_fkey FOREIGN KEY (assigned_supervisor_id) REFERENCES users(id);
ALTER TABLE public.reminders ADD CONSTRAINT reminders_internal_approved_by_fkey FOREIGN KEY (internal_approved_by) REFERENCES users(id);
ALTER TABLE public.reminders ADD CONSTRAINT reminders_internal_sales_id_fkey FOREIGN KEY (internal_sales_id) REFERENCES users(id);
ALTER TABLE public.reminders ADD CONSTRAINT reminders_installer_user_id_fkey FOREIGN KEY (installer_user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE public.reminders ADD CONSTRAINT reminders_pic_id_fkey FOREIGN KEY (pic_id) REFERENCES users(id);
ALTER TABLE public.reminders ADD CONSTRAINT reminders_warranty_years_check CHECK ((warranty_years = ANY (ARRAY[1, 2, 3])));
ALTER TABLE public.sql_diterapkan ADD CONSTRAINT sql_diterapkan_pkey PRIMARY KEY (berkas);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_pkey PRIMARY KEY (id);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_name_key UNIQUE (name);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_username_key UNIQUE (username);
ALTER TABLE public.tech_note_folders ADD CONSTRAINT tech_note_folders_pkey PRIMARY KEY (id);
ALTER TABLE public.tech_note_folders ADD CONSTRAINT tech_note_folders_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES tech_note_folders(id) ON DELETE SET NULL;
ALTER TABLE public.tech_note_folders ADD CONSTRAINT tech_note_folders_category_check CHECK (((category IS NULL) OR (category = ANY (ARRAY['display'::text, 'middleware'::text, 'software'::text]))));
ALTER TABLE public.tech_note_history ADD CONSTRAINT tech_note_history_pkey PRIMARY KEY (id);
ALTER TABLE public.tech_note_history ADD CONSTRAINT tech_note_history_tech_note_id_fkey FOREIGN KEY (tech_note_id) REFERENCES tech_notes(id) ON DELETE CASCADE;
ALTER TABLE public.tech_note_history ADD CONSTRAINT tech_note_history_action_check CHECK ((action = ANY (ARRAY['submitted'::text, 'approved'::text, 'revision_requested'::text, 'rejected'::text, 'resubmitted'::text])));
ALTER TABLE public.tech_notes ADD CONSTRAINT tech_notes_pkey PRIMARY KEY (id);
ALTER TABLE public.tech_notes ADD CONSTRAINT tech_notes_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES tech_note_folders(id) ON DELETE RESTRICT;
ALTER TABLE public.tech_notes ADD CONSTRAINT tech_notes_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'revision'::text, 'rejected'::text])));
ALTER TABLE public.ticket_support_assignment ADD CONSTRAINT ticket_support_assignment_pkey PRIMARY KEY (id);
ALTER TABLE public.ticket_support_assignment ADD CONSTRAINT ticket_support_assignment_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES users(id);
ALTER TABLE public.ticket_support_assignment ADD CONSTRAINT ticket_support_assignment_project_id_fkey FOREIGN KEY (project_id) REFERENCES reminders(id) ON DELETE CASCADE;
ALTER TABLE public.ticket_support_assignment ADD CONSTRAINT ticket_support_assignment_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.tickets ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);
ALTER TABLE public.tickets ADD CONSTRAINT tickets_reminder_id_fkey FOREIGN KEY (reminder_id) REFERENCES reminders(id) ON DELETE SET NULL;
ALTER TABLE public.tickets ADD CONSTRAINT tickets_priority_check CHECK ((priority = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text, 'Critical'::text])));
ALTER TABLE public.tickets ADD CONSTRAINT tickets_status_check CHECK ((status = ANY (ARRAY['Waiting Approval'::text, 'Pending'::text, 'Call'::text, 'Onsite'::text, 'In Progress'::text, 'Pending Action'::text, 'Solved'::text, 'Overdue'::text, 'Rejected'::text, 'Returned to PTS'::text, 'Cancelled'::text, 'Warranty'::text, 'Out Of Warranty'::text, 'Waiting PO from Sales'::text, 'Submit RMA'::text, 'Waiting sparepart'::text, 'Process Repair'::text]))) NOT VALID;
ALTER TABLE public.user_credentials ADD CONSTRAINT user_credentials_pkey PRIMARY KEY (id);
ALTER TABLE public.user_credentials ADD CONSTRAINT user_credentials_user_id_key UNIQUE (user_id);
ALTER TABLE public.user_credentials ADD CONSTRAINT user_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_sessions ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.user_sessions ADD CONSTRAINT user_sessions_token_hash_key UNIQUE (token_hash);
ALTER TABLE public.user_sessions ADD CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_supervisor_mappings ADD CONSTRAINT user_supervisor_mappings_pkey PRIMARY KEY (id);
ALTER TABLE public.user_supervisor_mappings ADD CONSTRAINT user_supervisor_mappings_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_supervisor_mappings ADD CONSTRAINT user_supervisor_mappings_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.users ADD CONSTRAINT users_username_key UNIQUE (username);
ALTER TABLE public.users ADD CONSTRAINT users_atasan_id_fkey FOREIGN KEY (atasan_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE public.users ADD CONSTRAINT users_access_level_check CHECK ((access_level = ANY (ARRAY['full'::text, 'guest'::text])));
ALTER TABLE public.users ADD CONSTRAINT users_incentive_brand_scope_check CHECK (((incentive_brand_scope IS NULL) OR (incentive_brand_scope = ANY (ARRAY['MVI'::text, 'IVP'::text]))));
ALTER TABLE public.users ADD CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'team'::text, 'guest'::text])));
