-- ═══════════════════════════════════════════════════════════════════════════
-- 03. INDEXES (selain yang sudah dibuat otomatis oleh PK/UNIQUE di 02_constraints.sql)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE INDEX idx_activity_ticket_id ON public.activity_logs USING btree (ticket_id);
CREATE INDEX idx_audit_trail_action ON public.audit_trail USING btree (action);
CREATE INDEX idx_audit_trail_created ON public.audit_trail USING btree (created_at DESC);
CREATE INDEX idx_audit_trail_module ON public.audit_trail USING btree (module);
CREATE INDEX idx_audit_trail_user_id ON public.audit_trail USING btree (user_id);
CREATE INDEX idx_team_entries_date ON public.daily_report_team_entries USING btree (report_date DESC);
CREATE INDEX idx_team_entries_entered_by ON public.daily_report_team_entries USING btree (entered_by);
CREATE INDEX idx_team_entries_member ON public.daily_report_team_entries USING btree (member_user_id);
CREATE INDEX idx_daily_reports_date ON public.daily_reports USING btree (report_date DESC);
CREATE INDEX idx_daily_reports_division ON public.daily_reports USING btree (sales_division);
CREATE INDEX idx_daily_reports_user ON public.daily_reports USING btree (user_id);
CREATE INDEX idx_form_reviews_batch_id ON public.form_reviews USING btree (batch_id) WHERE (batch_id IS NOT NULL);
CREATE INDEX idx_freviews_guest_user ON public.form_reviews USING btree (guest_user_id);
CREATE INDEX idx_freviews_sales_user ON public.form_reviews USING btree (sales_user_id);
CREATE INDEX idx_incentive_disbursements_periode ON public.incentive_disbursements USING btree (periode);
CREATE INDEX idx_incentive_disbursements_person ON public.incentive_disbursements USING btree (person_name);
CREATE INDEX idx_incentive_disbursements_project ON public.incentive_disbursements USING btree (project_id);
CREATE INDEX idx_incentive_projects_handler ON public.incentive_projects USING btree (handler_name);
CREATE INDEX idx_incentive_projects_periode ON public.incentive_projects USING btree (periode);
CREATE INDEX idx_incentive_projects_reminder ON public.incentive_projects USING btree (reminder_id);
CREATE INDEX incentive_scheme_settings_terbaru ON public.incentive_scheme_settings USING btree (updated_at DESC);
CREATE INDEX idx_incentive_splits_project ON public.incentive_splits USING btree (project_id);
CREATE INDEX idx_incentive_splits_tranche ON public.incentive_splits USING btree (tranche_id);
CREATE INDEX idx_incentive_tranches_project ON public.incentive_tranches USING btree (project_id);
CREATE INDEX idx_incentive_tranches_year ON public.incentive_tranches USING btree (payment_year, status);
CREATE UNIQUE INDEX incentive_tranches_unik_per_proyek ON public.incentive_tranches USING btree (project_id, tranche_number);
CREATE INDEX idx_ksm_member_id ON public.kpi_snapshot_members USING btree (member_id);
CREATE INDEX idx_ksm_snapshot_id ON public.kpi_snapshot_members USING btree (snapshot_id);
CREATE INDEX idx_late_ticket_parent ON public.late_ticket_links USING btree (parent_project_id);
CREATE INDEX idx_lc_answers_attempt ON public.lc_answers USING btree (attempt_id);
CREATE INDEX idx_lc_answers_user ON public.lc_answers USING btree (user_id);
CREATE INDEX idx_lc_questions_material ON public.lc_questions USING btree (material_id);
CREATE INDEX idx_lc_questions_type ON public.lc_questions USING btree (question_type);
CREATE INDEX lc_questions_urutan_idx ON public.lc_questions USING btree (material_id, batch_name, urutan);
CREATE INDEX idx_lc_attempts_grading_status ON public.lc_quiz_attempts USING btree (grading_status);
CREATE INDEX idx_lc_attempts_pending ON public.lc_quiz_attempts USING btree (quiz_session_id) WHERE (grading_status = 'pending_review'::text);
CREATE INDEX idx_lc_attempts_session ON public.lc_quiz_attempts USING btree (quiz_session_id);
CREATE INDEX idx_lc_attempts_user ON public.lc_quiz_attempts USING btree (user_id);
CREATE INDEX idx_lc_sessions_active ON public.lc_quiz_sessions USING btree (is_active);
CREATE INDEX idx_lc_sessions_type ON public.lc_quiz_sessions USING btree (session_type);
CREATE INDEX idx_login_attempts_ip ON public.login_attempts USING btree (ip_address, attempted_at);
CREATE INDEX idx_login_attempts_username ON public.login_attempts USING btree (username, attempted_at);
CREATE INDEX idx_notifications_created ON public.notifications USING btree (created_at DESC);
CREATE INDEX idx_notifications_unread ON public.notifications USING btree (user_id, is_read) WHERE (is_read = false);
CREATE INDEX idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE INDEX overdue_settings_set_by_idx ON public.overdue_settings USING btree (set_by);
CREATE INDEX overdue_settings_ticket_id_idx ON public.overdue_settings USING btree (ticket_id);
CREATE INDEX idx_otp_username ON public.password_reset_otps USING btree (username);
CREATE INDEX idx_picket_holidays_date ON public.picket_holidays USING btree (date);
CREATE INDEX idx_piket_produk_lain_kegiatan ON public.piket_produk_lain USING btree (kegiatan_id);
CREATE INDEX idx_piket_produk_lain_piket ON public.piket_produk_lain USING btree (piket_id);
CREATE INDEX idx_progress_actions_issue ON public.progress_actions USING btree (issue_id);
CREATE INDEX idx_progress_actions_target ON public.progress_actions USING btree (target_date) WHERE (target_date IS NOT NULL);
CREATE INDEX idx_progress_components_loc ON public.progress_components USING btree (location_id);
CREATE INDEX idx_progress_issues_component ON public.progress_issues USING btree (component_id) WHERE (component_id IS NOT NULL);
CREATE INDEX idx_progress_issues_due ON public.progress_issues USING btree (due_date) WHERE (due_date IS NOT NULL);
CREATE INDEX idx_progress_issues_location ON public.progress_issues USING btree (location_id) WHERE (location_id IS NOT NULL);
CREATE INDEX idx_progress_issues_project ON public.progress_issues USING btree (project_id);
CREATE INDEX idx_progress_issues_status ON public.progress_issues USING btree (status);
CREATE INDEX idx_plocations_pic_user ON public.progress_locations USING btree (pic_user_id);
CREATE INDEX idx_plocations_sales_user ON public.progress_locations USING btree (sales_user_id);
CREATE INDEX idx_progress_locations_origin ON public.progress_locations USING btree (origin) WHERE (origin = 'auto_reminder'::text);
CREATE INDEX idx_progress_locations_project ON public.progress_locations USING btree (project_id);
CREATE INDEX idx_progress_locations_target ON public.progress_locations USING btree (target_date) WHERE (target_date IS NOT NULL);
CREATE UNIQUE INDEX uq_progress_locations_source_reminder ON public.progress_locations USING btree (source_reminder_id) WHERE (source_reminder_id IS NOT NULL);
CREATE INDEX idx_pprojects_sales_user ON public.progress_projects USING btree (sales_user_id);
CREATE INDEX idx_progress_projects_target ON public.progress_projects USING btree (target_date) WHERE (target_date IS NOT NULL);
CREATE INDEX idx_progress_projects_token ON public.progress_projects USING btree (share_token) WHERE (share_token IS NOT NULL);
CREATE INDEX idx_preq_assign_user ON public.project_requests USING btree (assign_user_id);
CREATE INDEX idx_preq_sales_user ON public.project_requests USING btree (sales_user_id);
CREATE INDEX idx_project_requests_internal_sales ON public.project_requests USING btree (internal_sales_id) WHERE (internal_sales_id IS NOT NULL);
CREATE INDEX idx_project_requests_ivp ON public.project_requests USING btree (ivp_assignee);
CREATE INDEX idx_pts_team_staff ON public.pts_team_mappings USING btree (staff_user_id);
CREATE INDEX idx_pts_team_supervisor ON public.pts_team_mappings USING btree (supervisor_user_id);
CREATE INDEX idx_reminders_assign_user ON public.reminders USING btree (assign_user_id);
CREATE INDEX idx_reminders_assigned_supervisor ON public.reminders USING btree (assigned_supervisor_id) WHERE (assigned_supervisor_id IS NOT NULL);
CREATE INDEX idx_reminders_batch_id ON public.reminders USING btree (batch_id) WHERE (batch_id IS NOT NULL);
CREATE INDEX idx_reminders_incentive_excluded ON public.reminders USING btree (incentive_excluded) WHERE (incentive_excluded IS TRUE);
CREATE INDEX idx_reminders_internal_sales ON public.reminders USING btree (internal_sales_id) WHERE (internal_sales_id IS NOT NULL);
CREATE INDEX idx_reminders_sales_user ON public.reminders USING btree (sales_user_id);
CREATE INDEX reminders_incentive_group_idx ON public.reminders USING btree (incentive_group_id) WHERE (incentive_group_id IS NOT NULL);
CREATE INDEX idx_tech_note_history_note_id ON public.tech_note_history USING btree (tech_note_id, created_at);
CREATE INDEX idx_tech_notes_author_status ON public.tech_notes USING btree (author_id, status, reviewed_at);
CREATE INDEX idx_tech_notes_folder ON public.tech_notes USING btree (folder_id);
CREATE INDEX idx_tech_notes_submitted ON public.tech_notes USING btree (submitted_at DESC);
CREATE INDEX idx_ticket_support_project ON public.ticket_support_assignment USING btree (project_id);
CREATE INDEX idx_tickets_assign_user ON public.tickets USING btree (assign_user_id);
CREATE INDEX idx_tickets_assigned ON public.tickets USING btree (assign_name);
CREATE INDEX idx_tickets_date ON public.tickets USING btree (date);
CREATE INDEX idx_tickets_project ON public.tickets USING btree (project_name);
CREATE INDEX idx_tickets_reminder ON public.tickets USING btree (reminder_id) WHERE (reminder_id IS NOT NULL);
CREATE INDEX idx_tickets_sales_user ON public.tickets USING btree (sales_user_id);
CREATE INDEX idx_tickets_status ON public.tickets USING btree (status);
CREATE INDEX idx_user_sessions_exp ON public.user_sessions USING btree (expires_at);
CREATE INDEX idx_user_sessions_token ON public.user_sessions USING btree (token_hash);
CREATE INDEX idx_user_sessions_user ON public.user_sessions USING btree (user_id);
CREATE INDEX idx_users_atasan_id ON public.users USING btree (atasan_id);
CREATE INDEX idx_users_role ON public.users USING btree (role);
CREATE INDEX idx_users_username ON public.users USING btree (username);
